services:
  app:
    image: app:prod
    container_name: app.prod
    build:
      context: ./app
    ports:
      - 80:3000
    env_file:
      - .env.prod
    working_dir: /app
    command: sh -c "node build/index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network
      - app-internal
    

  db:
    image: postgres:17
    container_name: app.db
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.prod.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-internal
  
  migrate:
    image: app-migrate:prod
    container_name: app.migrate
    build:
      context: ./app
      dockerfile: Dockerfile.migrate
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-internal

networks:
  app-network:
    name: app-network
    driver: bridge
  app-internal:
    name: app-internal
    driver: bridge
    external: false
    internal: true

volumes:
  db_data:
    driver: local
    name: db.prod
