# /// ./docker-compose.yml

services:
  app:
    image: bhm_ims:dev
    container_name: bhm_ims.dev
    build:
      context: ./app
      target: development
    ports:
      - 5173:5173
    env_file:
      - .env.dev
    volumes:
      - ./app:/app:cached
      - /app/node_modules
    working_dir: /app
    command: sh -c "pnpm db:migrate && pnpm dev --host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bhm_ims
      - bhm_ims-internal
    

  db:
    image: postgres:17
    container_name: bhm_ims.db.dev
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - bhm_ims-internal
      - bhm_ims
  
  # drizzle-studio:
  #   image: bhm_ims:drizzle-studio
  #   container_name: bhm_ims.drizzle-studio
  #   ports:
  #     - 4983:4983
  #     env_file:
  #       - .env.dev
  #     depends_on:
  #       db:
  #         condition: service_healthy
  #     restart: unless-stopped
  #     command: npx drizzle-kit studio --host=0.0.0.0 --port 4983
  #     networks:
  #       - bhm_ims-internal
  #       - bhm_ims

networks:
  bhm_ims:
    name: bhm_ims
    driver: bridge
  bhm_ims-internal:
    name: bhm_ims-internal
    internal: true

volumes:
  db_data:
    driver: local
    name: bhm_ims.db.dev
  node_modules:
    name: bhm_ims.node_modules
